import type { NextPage } from "next";
import Head from "next/head";
// import Image from "next/image";
// import styles from "../styles/Project.module.css";
import { Auth, } from "aws-amplify";
import Link from "next/link";
import { ConsoleLogger } from "@aws-amplify/core";
//import CodeBlock from "../../components/CodeBlock";
import { useRouter } from "next/router";
//import CodeControlBar from "../../components/CodeControlBar";
import { API, graphqlOperation } from "aws-amplify";
import { getProject, listProjects } from "../../graphql/queries";
import { Project, ListProjectsQuery } from "../../API";
import { useEffect, useState } from "react";
//import { useUser } from "../context/AuthContext"
import awsconfig from "../../aws-exports"
// import GraphQLAPI from "@aws-amplify/api-graphql";
// import Login from "../login";

// const QUERY_LIST_OF_COUNTRIES = `
//   {
//     query ListProjects {
//       pid
//       pName
//     }
//   }
// `;


export default function Home(props:any) {
  
  API.configure(awsconfig);


  const router = useRouter();
  const { pid, pName } = router.query;
  console.log(pid);
  console.log(pName);
  //const { user } = useUser();
  const [project,setProject ] = useState<Project[]>([]) ;
  // project = 10 setProject(10)
  useEffect(() => {
    
    const fetchProject = async ()  => {
      const project = await API.graphql(graphqlOperation(listProjects));
      console.log(project)
    };

    fetchProject();
  }, []);
  
  const signOut = async () => {
    try {
      await Auth.signOut();
      router.push("/")
    } catch (error) {
      console.log('error signing out ', error);
    }
  };

 // <CodeBlock language="python" width="100vw" height="90vh" />

  return (
    

    <div>
       
      <Head>
        <title>Code Code Guide fuck you </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        
        
        <div style={{color: "white", backgroundColor: "black", width:"100%"}}>Code Code Guide</div>
        {/* <nav style={{backgroundColor: "grey"}}>
            <ul>
                <li>
                    <Link href='/'>Back To Home</Link>
                </li>
            </ul>
        </nav> */}






    

        {/* 
        

            //    {project.map((Project) => ())}
        
        
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}

        {/* <div>
          <button onClick={()=>signOut()}>FUCK YOU AWS</button>
        </div> */}

          {/* <div>
            <button onClick={props.signUp}>Help</button>
          </div> */}
        
      </main>
    </div>
  );
};
