import type { NextPage } from "next";
import Head from "next/head";
// import Image from "next/image";
// import styles from "../styles/Project.module.css";
import { Auth } from "aws-amplify";
import Link from "next/link";
import {useRouter} from "next/router";
import { ConsoleLogger } from "@aws-amplify/core";

export default function Home(props:any) {
  // Auth.currentAuthenticatedUser().then((user) => {
  //   console.log(user);
  // });
  const router = useRouter()

  const signOut = async () => {
    try {
      await Auth.signOut();
      // setLoggedIn(false)
      router.push("/");
    } catch (error) {
      console.log('errror signing out ', error);
    }
  };

  return (    
    <div>
      <Head>
        <title>Code Code Guide fuck you </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        
        <div style={{color: "white", backgroundColor: "black", width:"100%"}}>Code Code Guide</div>
        <nav style={{backgroundColor: "grey"}}>
            <ul>
                <li>
                    <Link href='/'>Back To Home</Link>
                </li>
            </ul>
        </nav>

        <div>
          View your project <br />
          //...list projects here
        </div>

        <div>
          {/* <Link href="/"> */}
            <button onClick={() => signOut()}>FUCK YOU AWS</button>
          {/* </Link> */}
        </div>

          <div>
            {/* <Link href="/"> */}
              <button onClick={props.signUp}>Help</button>
            {/* </Link>  */}
          </div>
        
      </main>
    </div>
  );
};
