import type { NextPage } from "next";
import Head from "next/head";
import Link from 'next/link'
// import Image from "next/image";
import styles from "../styles/Home.module.css";
// import { Auth } from "aws-amplify";
import React from 'react';
import Login from "../component/login";
// import Login from "./login";

export default function Home(props:any) {
  Auth.currentAuthenticatedUser().then((user) => {
    console.log(user);
  });
  return (
    
    <div>
      <Head>
        <title>Code Code Guide fuck you </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <div className={styles.header}>Code Code Guide</div>

        <div className={styles.nav}>
          Gonna fk up
          {/* <code className={styles.code}>pages/index.tsx</code> */}
        </div>

        <div className={styles.content}>
          <h1>Welcome to CodeCodeGuide! <br />
          Log in to start coding now!</h1>
        </div>

        <div>
          <button onClick={props.signOut}> FUCK YOU AWS</button>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

// export default Home;
