import type { NextPage } from "next";
import Head from "next/head";
import Link from 'next/link'
import Logo from "next/image";
import styles from "../styles/Home.module.css";
// import { Auth } from "aws-amplify";
import React from 'react';
import Login from "../component/login";
// import Login from "./login";

// const LoginButton = React.forwardRef(({ onClick, href }, ref) => {
//   return (
//     <a href={href} onClick={onClick} ref={ref}>Click here to Login!</a>
//   )
// })

export default function Home(props:any) {
  return (    
    <div>
      <div style={{color: "white", backgroundColor: "black", width:"100%"}}>
      <Head>
        <title>Code Code Guide fuck you </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      
        <h1 className={styles.header}><Logo src="/Logo.png" alt="me" width="82" height="74" />CodeCodeGuide</h1>

        <nav style={{backgroundColor: "grey", width: "100%"}}>
            <ul>
                <li>
                    <Link href='/'>Home</Link>
                </li>
            </ul>
        </nav>
        

        <div className={styles.content}>

          <h1>Welcome to CodeCodeGuide! <br />
          Log in to start coding now!</h1>
        </div>
        <div>
          <Link href='./signin'>Click here to Login!</Link>
        </div>
        
      </main>
      </div>
      </div>

  );
};

// export default Home;
